language: python
python:
      - "2.7"
      - "3.6"
sudo: false
install:
      - make setup
      - make update
      - nvm install 6.10
      - nvm use 6.10
before_script:
      - pip install flake8
      # stop the build if there are Python syntax errors or undefined names
      - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
      # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - make lint-python
      - make lint-js
script:
      - make test
notifications:
      email: false
